kind = "web"
previewPath = "/"
title = "NexTerm"
version = "1.0.0"
id = "artifacts/nexterm"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20608

[services.development]
run = "pnpm --filter @workspace/nexterm run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nexterm", "run", "build" ]
publicDir = "artifacts/nexterm/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20608"
BASE_PATH = "/"
